_wandb:
    value:
        cli_version: 0.19.7.dev1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 6
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 6
                - 53
                - 55
            "3":
                - 3
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7.dev1
            "8":
                - 1
                - 5
            "12": 0.19.7.dev1
            "13": linux-x86_64
assume_model_classifications:
    value: true
dataset_config:
    value: 1
eval_on:
    value: test
model_class:
    value: SCNN_TPL3
num_to_use_per_class:
    value: 1000
num_training_folds:
    value: 2
num_val_test_folds:
    value: 2
prop_to_use:
    value: 1
sweep_id:
    value: wh844aab
threshold:
    value: 0.55
vae_config:
    value:
        beta: 5
        hidden_dim: 256
        input_dim: 2403
        latent_dim: 16
        learning_rate: 0.001
        num_epochs: 128
        output_dim: 2403
